build:
  environment:
    python: 3.11.2
  dependencies:
    override:
      - "pip install -r requirements/core.txt -r requirements/test.txt"
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
          - py-scrutinizer-run

filter:
  paths:
    - "byceps/"
  excluded_paths:
    - "byceps/static/behavior/vendor/"

tools:
  python_analyzer:
    config:
      duplication_detector:
        enabled: false
