version: "3.9"

x-byceps-base: &byceps-base
  image: "the0mikkel/byceps:latest"
  volumes:
    - type: volume
      source: byceps-data
      target: /home/byceps/data
  depends_on:
    - db
    - redis

x-byceps-base-env: &byceps-base-env
    REDIS_URL: "redis://redis/0"
    SECRET_KEY: /run/secrets/secret_key
    SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://byceps:byceps@db/byceps"

services:

  db:
    image: "postgres:16"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: byceps
      POSTGRES_USER: byceps
    networks:
      - byceps

  redis:
    image: "redis:7"
    networks:
      - byceps

  byceps:
    <<: *byceps-base
    environment:
      <<: *byceps-base-env
    depends_on:
      - db
      - redis
    networks:
      - byceps
      - proxy
    volumes:
      - ./config:/home/byceps/config:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  byceps-worker:
    <<: *byceps-base
    environment:
      <<: *byceps-base-env
      APP_MODE: worker
    depends_on:
      - byceps
    networks:
      - byceps
    command: ./worker.py

  web:
    image: nginx
    volumes:
      # Nginx configuration
      - ./docker/nginx/includes:/etc/nginx/includes:ro
      - ./docker/nginx/templates:/etc/nginx/templates:ro
      # Static data files, not hosted through Byceps
      - ./data:/var/www/byceps/data:ro
      - ./sites:/var/www/byceps/sites:ro
    depends_on:
      - byceps
    environment:
      # The hostnames that the web server should listen on and return the admin
      SERVER_NAME_ADMIN: byceps-admin.localhost
      # THe hostnames that the web server should listen on and return the site
      SERVER_NAME_SITE: byceps-site.localhost
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

secrets:
  secret_key:
    # To generate a secret key file, run:
    # `docker compose run --rm byceps-admin byceps generate-secret-key > ./secret_key.txt`
    file: ./secret_key.txt

volumes:
  byceps-data:
  db-data:

networks:
  byceps:
  proxy:
