version: "3.9"

x-byceps-base: &byceps-base
  image: "${DC_DOCKER_ORG:-ghcr.io/byceps}/byceps:${DC_DOCKER_VERSION:-latest}"
  volumes:
    - ./data:/home/byceps/data
    - ./sites:/home/byceps/sites
    - ./config:/home/byceps/config:ro
  depends_on:
    - db
    - redis

x-byceps-base-env: &byceps-base-env
    REDIS_URL: "redis://redis/0"
    SECRET_KEY: /run/secrets/secret_key
    SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://${DC_DB_USER:-byceps}:${DC_DB_PASSWORD:-byceps}@db/byceps"

services:

  db:
    image: "postgres:15"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DC_DB_PASSWORD:-byceps}
      POSTGRES_USER: ${DC_DB_USER:-byceps}
    networks:
      - byceps

  redis:
    image: "redis:7"
    networks:
      - byceps

  byceps:
    <<: *byceps-base
    environment:
      <<: *byceps-base-env
      BYCEPS_APPS_CONFIG: /home/byceps/config/apps.toml
    networks:
      - byceps
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${DC_HEALTH_CHECK_HOSTNAME:-byceps-admin.localhost}t:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  byceps-worker:
    <<: *byceps-base
    environment:
      <<: *byceps-base-env
      APP_MODE: worker
    networks:
      - byceps
    command: ./worker.py

  web:
    image: nginx
    volumes:
      # Nginx configuration
      - ./docker/nginx/includes:/etc/nginx/includes:ro
      - ./docker/nginx/templates:/etc/nginx/templates:ro
      # Static data files, not hosted through Byceps
      - ./data:/var/www/byceps/data:ro
      - ./sites:/var/www/byceps/sites:ro
      - ./byceps/static:/var/www/byceps/byceps/static:ro
    depends_on:
      - byceps
    environment:
      # The hostnames that the web server should listen on and return the admin
      SERVER_NAME_ADMIN: ${DC_ADMIN_HOSTNAMES:-byceps-admin.localhost}
      # THe hostnames that the web server should listen on and return the site
      SERVER_NAME_SITE: ${DC_SITE_HOSTNAMES:-byceps-site.localhost}
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${DC_HEALTH_CHECK_HOSTNAME:-byceps-admin.localhost}t:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

secrets:
  secret_key:
    # To generate a secret key file, run:
    # `docker compose run --rm byceps-admin byceps generate-secret-key > ./secret_key.txt`
    file: ./secret_key.txt

volumes:
  db-data:

networks:
  byceps:
  proxy:
